version: "3"
services:
  app:
    build:
      context: .
      dockerfile: ${DOCKERFILE}
    container_name: applicant_container
    ports:
      - "50000:3000"
    env_file:
      - .env
    volumes:
      - .:/app
    command: bash -c "rm -f tmp/pids/server.pid && rails db:migrate RAILS_ENV=development && rails s -p 3000 -b '0.0.0.0'"
